version: "3.8"

services:
  postgres:
    container_name: camunda-postgres
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  keycloak:
     container_name: keycloak
     image: jboss/keycloak:latest
     environment:
       DB_VENDOR: POSTGRES
       DB_ADDR: postgres
       DB_DATABASE: postgres
       DB_SCHEMA: keycloak
       DB_USER: postgres
       DB_PASSWORD: postgres
       KEYCLOAK_USER: admin
       KEYCLOAK_PASSWORD: admin
     ports:
          - "8000:8080"
     volumes:
       - ./imports:/opt/jboss/keycloak/imports
     command:
       - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
     depends_on:
          - postgres

volumes:
  db:
    driver: local